// =========================================
//  TRANSLATION DICTIONARY
// =========================================
const translations = {
    fr: {
        // NAV
        "nav.accueil": "Accueil",
        "nav.activites": "Activités",
        "nav.entreprise": "Entreprise",
        "nav.veille": "Veille",
        "nav.contact": "Me contacter",
        "nav.links": "Liens Rapides",
        "nav.social": "Réseaux",
        "nav.mentions": "Mentions Légales",
        "nav.confidentialite": "Confidentialité",
        // HERO
        "hero.subtitle": "Étudiant en BTS SIO – option SISR",
        "hero.title": "Futur Administrateur Système & Réseau",
        "hero.desc": "En deuxième année de BTS SIO option SISR, je me forme à l'<strong>administration d'infrastructures</strong> et à la <strong>cybersécurité</strong>. Ce portfolio retrace mon parcours, mes projets et mes compétences.",
        "hero.cta": "Voir mes projets",
        // SECTIONS - INDEX
        "section.skills": "Compétences",
        "index.option.sisr.title": "Option SISR",
        "index.option.sisr.full": "Solutions d'Infrastructure, Systèmes et Réseaux",
        "index.option.sisr.desc": "Administration de serveurs Windows et Linux, gestion de réseaux (VLAN, routage, Wi-Fi), sécurité (pare-feu, VPN, sauvegardes), virtualisation (Proxmox, VMware) et supervision d'infrastructures.",
        "index.option.slam.title": "Option SLAM",
        "index.option.slam.full": "Solutions Logicielles et Applications Métiers",
        "index.option.slam.desc": "Développement d'applications web et mobiles, conception de bases de données, programmation orientée objet, gestion de projets logiciels et tests.",
        "index.option.chosen": "✅ Mon choix",
        "index.option.why_sisr": "<strong>Pourquoi la SISR ?</strong> Ce qui m'a attiré, c'est le côté concret : monter un serveur, configurer un réseau, sécuriser une infrastructure et résoudre des problèmes en temps réel. La SISR correspond au métier que je veux exercer au quotidien.",
        "index.skills.intro": "Le BTS SIO propose deux spécialisations. J'ai choisi <strong>SISR (Solutions d'Infrastructure, Systèmes et Réseaux)</strong> parce que c'est ce qui me correspond : travailler sur les serveurs, le réseau, la sécurité et l'exploitation au quotidien. On y apprend à mettre en place des services (Active Directory, DNS, DHCP, virtualisation…), à les superviser et à gérer les incidents de manière structurée.",
        "index.skills.list1": "Installation et configuration de postes clients (déploiement OS, pilotes, outils métier)",
        "index.skills.list2": "Administration de serveurs et réseaux (sauvegardes, supervision, VLAN, DHCP/DNS)",
        "index.skills.list3": "Sécurisation des systèmes et des accès (droits, chiffrement, mises à jour, pare-feu)",
        "index.skills.list4": "Support utilisateur, documentation technique et rédaction de procédures",
        "skills.os": "Systèmes",
        "skills.net": "Réseaux",
        "skills.sec": "Sécurité",
        "skills.tools": "Outils & Soft Skills",
        "section.projects": "Derniers Projets",
        "index.projects.title": "Projets Récents",
        "index.projects.intro": "Voici quelques-uns des projets que j'ai réalisés, en cours de formation ou à titre personnel. Ils couvrent l'administration système, le réseau et la virtualisation.",
        "index.projects.btn": "📂 Voir tous mes projets",
        "index.school.title": "Mon école — Faculté des Métiers de l'Essonne",
        "index.school.text": "Je prépare mon BTS SIO à la <strong>FDME</strong>, en alternance. Ce format me permet de faire le lien entre ce que j'apprends en cours et ce que je pratique en entreprise. C'est comme ça que je progresse le plus vite : en appliquant directement sur le terrain.",
        "index.school.btn": "Découvrir la FDME",
        "index.cv.title": "Mon CV",
        "index.cv.text": "Mon CV regroupe mon parcours, mes compétences techniques et les missions que j'ai réalisées en entreprise. Il est régulièrement mis à jour.",
        "index.cv.btn": "📄 Télécharger mon CV (PDF)",
        "section.contact": "Restons en contact",
        // ENTREPRISE
        "company.title": "Mon alternance chez Althec",
        "company.intro_title": "Présentation de l'entreprise",
        "company.desc": "<strong>ALTHEC Sécurité Systèmes</strong> est une PME spécialisée dans la sûreté électronique. Elle accompagne ses clients à chaque étape : étude des besoins, choix de la solution, installation sur site, puis maintenance sur le long terme. La relation est directe avec le client, ce qui permet de s'adapter rapidement.",
        "company.details.social": "Raison sociale :",
        "company.details.legal": "Forme juridique :",
        "company.details.creation": "Date de création :",
        "company.details.hq": "Siège social :",
        "company.details.sector": "Secteur :",
        "company.details.workforce": "Effectif :",
        "company.details.zone": "Zone géographique :",
        "company.details.clients": "Typologie clientèle :",
        "company.details.turnover": "Chiffre d'affaires :",
        "company.activity.title": "Activité principale",
        "company.activity.text": "Althec conçoit et installe des systèmes de protection adaptés à chaque site : vidéosurveillance IP, centrales d'alarme, contrôle d'accès par badge, interphonie. Une fois le système en place, l'entreprise assure le suivi avec de la maintenance préventive et corrective.",
        "company.services.title": "Offre de services",
        "company.services.list1.title": "Étude & conseil :",
        "company.services.list1.desc": "analyse des risques, recommandations techniques, chiffrage",
        "company.services.list2.title": "Installation :",
        "company.services.list2.desc": "câblage, pose du matériel, configuration et mise en service",
        "company.services.list3.title": "Intégration réseau :",
        "company.services.list3.desc": "adressage IP, accès distant sécurisé, supervision",
        "company.services.list4.title": "Maintenance :",
        "company.services.list4.desc": "interventions préventives et correctives, support technique",
        // ACTIVITES - GENERAL
        "projects.title": "Activités",
        "projects.search_placeholder": "Rechercher un projet (ex. MediaWiki, GLPI, Plex, Pi-hole)…",
        "projects.filter_all": "Tous",
        "projects.filter_network": "Réseau",
        "projects.filter_security": "Sécurité",
        "projects.filter_system": "Système",
        "projects.filter_web": "Web",
        "projects.intro": "Je présente ici mes projets réalisés en formation et ceux montés chez moi en autonomie. Chacun répond à un besoin concret ou à une envie d'approfondir un sujet.",
        "projects.school_title": "📘 Projets de formation",
        "projects.personal_title": "🛠️ Projets personnels",
        "projects.goal_label": "Objectif :",
        "projects.env_label": "Environnement :",
        "projects.material_label": "Matériel :",
        "projects.result_label": "Résultat :",
        "projects.btn_detail": "Voir le détail →",
        "projects.btn_pdf": "📄 Doc PDF",
        // ACTIVITES - CARDS
        "projects.mediawiki.title": "MediaWiki sous Windows",
        "projects.mediawiki.goal": "déployer un wiki interne pour centraliser les procédures techniques et les documentations d'exploitation.",
        "projects.mediawiki.list1": "Installation et configuration de XAMPP",
        "projects.mediawiki.list2": "Création de la BDD <code>mediawiki</code> via phpMyAdmin",
        "projects.mediawiki.list3": "Déploiement dans <code>C:\\xampp\\htdocs\\mediawiki</code>",
        "projects.mediawiki.list4": "Configuration de l'assistant + extensions (VisualEditor)",
        "projects.mediawiki.list5": "Mise en place des sauvegardes SQL et du répertoire images",
        "projects.glpi.title": "GLPI sous Windows",
        "projects.glpi.goal": "mettre en place une solution de helpdesk et de gestion de parc informatique.",
        "projects.glpi.list1": "Installation de la stack Web (Apache / PHP / MariaDB)",
        "projects.glpi.list2": "Création de la BDD <code>glpi</code> via phpMyAdmin",
        "projects.glpi.list3": "Déploiement dans <code>C:\\xampp\\htdocs\\glpi</code>",
        "projects.glpi.list4": "Configuration des profils, entités et SLA",
        "projects.glpi.list5": "Inventaire automatique avec FusionInventory",
        "projects.plex.title": "Serveur Plex sur NAS",
        "projects.plex.goal": "mettre en place un serveur multimédia pour centraliser et diffuser mes contenus à la maison.",
        "projects.plex.list1": "Déploiement de Plex Media Server via Docker",
        "projects.plex.list2": "Configuration des volumes persistants",
        "projects.plex.list3": "Organisation des bibliothèques (Films / Séries / Musiques)",
        "projects.plex.list4": "Accès multi-appareils (TV, mobile, PC)",
        "projects.plex.list5": "Activation du transcodage matériel",
        "projects.plex.result": "serveur stable, accessible depuis tous les appareils du foyer.",
        "projects.pihole.title": "Pi-hole sur Raspberry Pi",
        "projects.pihole.goal": "filtrer les publicités et les trackers au niveau DNS pour l'ensemble du réseau domestique.",
        "projects.pihole.list1": "Préparation du Raspberry Pi (OS, SSH, mises à jour)",
        "projects.pihole.list2": "Installation de Pi-hole et configuration DNS",
        "projects.pihole.list3": "Redirection du DNS de la box vers le Pi-hole",
        "projects.pihole.list4": "Ajout de listes de blocage (publicités, tracking, malwares)",
        "projects.pihole.list5": "Supervision via le tableau de bord web",
        "projects.pihole.list6": "Sauvegarde de la configuration et attribution d'une IP fixe",
        "projects.pihole.result": "navigation plus propre et réseau mieux protégé.",
        "projects.vpn.title": "Serveur VPN sur Raspberry Pi",
        "projects.vpn.goal": "pouvoir accéder à mon réseau local depuis l'extérieur, de manière sécurisée.",
        "projects.vpn.list1": "Durcissement du Raspberry Pi (SSH, pare-feu, fail2ban)",
        "projects.vpn.list2": "Déploiement du serveur VPN (WireGuard)",
        "projects.vpn.list3": "Génération des profils clients (PC et mobile)",
        "projects.vpn.list4": "Ouverture de port + DDNS sur la box Internet",
        "projects.vpn.list5": "Mise en place de règles pare-feu pour limiter l'accès",
        "projects.vpn.list6": "Tests depuis l'extérieur et rédaction de la documentation",
        "projects.vpn.result": "accès distant fonctionnel, chiffré et documenté.",
        "projects.restaurant.btn_site": "🌐 Accéder au site",
        // VEILLE
        "blog.title": "Veille Technologique",
        "blog.intro": "Dans le cadre du BTS SIO, je réalise une veille régulière sur les sujets qui touchent à mon futur métier : administration système, cybersécurité, évolutions réglementaires. Voici mes articles et analyses.",
        "blog.read_more": "Lire l'article complet →",
        "blog.read_analysis": "Lire l'analyse →",
        "blog.rss_title": "📡 Flux RSS — Actualités en temps réel",
        "blog.analysis.title": "📝 Mes Analyses d'Articles",
        "blog.analysis.intro": "Je sélectionne des articles en lien avec ma spécialité et j'en rédige une analyse personnelle, pour montrer que je comprends les enjeux derrière l'actualité technique.",
        "blog.analysis.badge": "📖 Analyse",
        "blog.analysis.summary_label": "<strong>Résumé de l'article :</strong>",
        "blog.analysis.my_analysis": "<strong>Mon analyse :</strong>",
        "blog.analysis1.date": "📅 10 Fév 2026",
        "blog.analysis1.title": "L'essor des passkeys : vers la fin des mots de passe ?",
        "blog.analysis1.source": "Source : IT-Connect",
        "blog.analysis1.summary": "Les passkeys (clés d'accès) remplacent progressivement les mots de passe classiques. Basées sur la norme FIDO2/WebAuthn, elles utilisent la biométrie ou un code PIN local pour authentifier l'utilisateur, sans jamais envoyer de secret au serveur. Google, Apple et Microsoft les intègrent désormais nativement dans leurs systèmes.",
        "blog.analysis1.analysis": "En tant que futur administrateur système, cette évolution m'intéresse directement. Les mots de passe sont souvent le point faible de la sécurité : phishing, réutilisation, mots de passe trop simples. Les passkeys règlent ces problèmes en supprimant le secret partagé entre le client et le serveur. Mais en entreprise, le déploiement soulève des questions concrètes : est-ce compatible avec l'Active Directory existant ? Comment gérer ça de manière centralisée ? Comment former les utilisateurs ? C'est une technologie que je suis de près.",
        "blog.analysis2.date": "📅 28 Jan 2026",
        "blog.analysis2.title": "NIS 2 : la nouvelle directive européenne de cybersécurité",
        "blog.analysis2.source": "Source : ANSSI",
        "blog.analysis2.summary": "La directive NIS 2, en vigueur depuis octobre 2024, élargit le nombre d'organisations concernées par des obligations de cybersécurité en Europe. Elle impose des mesures de gestion des risques, de déclaration d'incidents et de gouvernance à des milliers d'entités supplémentaires, y compris des PME et des collectivités.",
        "blog.analysis2.analysis": "NIS 2 va changer le quotidien des administrateurs système. Les entreprises vont devoir renforcer leurs politiques de sauvegarde, de supervision et de réponse aux incidents. Pour un technicien SISR comme moi, ça veut dire maîtriser les outils de détection (SIEM, IDS/IPS), documenter proprement les procédures et savoir réagir en cas de crise. C'est un cadre réglementaire qui donne encore plus de valeur à nos compétences.",
        "blog.stack_title": "📚 Ma Stack de Veille",
        "blog.cat_law": "Législation & Droit",
        "blog.cat_ia": "IA & Souveraineté",
        "blog.article1.date": "📅 15 Nov 2024",
        "blog.article1.source": "Source : IT-Connect",
        "blog.article1.title": "Windows Server 2025 : les nouveautés pour les admins",
        "blog.article1.desc": "Microsoft prépare la relève avec Windows Server 2025. Active Directory renforcé, Hotpatching, meilleures performances NVMe… Un tour d'horizon des fonctionnalités qui vont impacter l'administration système au quotidien.",
        "blog.article2.date": "📅 02 Oct 2024",
        "blog.article2.source": "Source : CNIL",
        "blog.article2.title": "RGPD : quel bilan économique après 6 ans ?",
        "blog.article2.desc": "Le respect de la vie privée est-il un frein ou un avantage pour les entreprises ? Retour sur les constats de la CNIL et les impacts concrets pour les DSI.",
        "blog.article3.date": "📅 28 Sept 2024",
        "blog.article3.source": "Source : ZDNet",
        "blog.article3.title": "Souveraineté numérique : l'enjeu de l'IA Open Source",
        "blog.article3.desc": "Avec Mistral AI et Hugging Face, la France a des cartes à jouer face aux géants américains. L'IA open source est un enjeu majeur pour l'indépendance technologique européenne.",
        // MISSIONS
        "missions.title": "🎯 Mes missions en entreprise",
        "missions.intro": "Pendant mon alternance chez Althec, j'ai travaillé sur deux axes principaux qui m'ont permis de développer mes compétences techniques sur le terrain.",
        "missions.network.title": "Configuration réseau",
        "missions.network.desc": "J'ai participé au paramétrage et au déploiement des équipements réseau chez les clients : switches, routeurs, NVR (enregistreurs vidéo réseau) et caméras IP. Cela incluait la configuration des VLAN, l'adressage IP, les règles de pare-feu et la mise en place d'accès distants sécurisés.",
        "missions.network.list1": "Configuration IP des caméras et NVR sur le réseau client",
        "missions.network.list2": "Paramétrage de switches (VLAN, trunk, PoE)",
        "missions.network.list3": "Mise en place d'accès distant sécurisé (VPN)",
        "missions.network.list4": "Tests de connectivité et dépannage sur le terrain",
        "missions.support.title": "Support technique client",
        "missions.support.desc": "J'ai assuré le support téléphonique et sur site pour aider les clients à résoudre leurs problèmes liés aux systèmes de sûreté. Ça impliquait du diagnostic de pannes, des interventions correctives et la rédaction de comptes-rendus.",
        "missions.support.list1": "Diagnostic et résolution d'incidents à distance",
        "missions.support.list2": "Interventions correctives directement sur site",
        "missions.support.list3": "Rédaction de rapports d'intervention",
        "missions.support.list4": "Formation des utilisateurs aux outils déployés",
        // PROJET
        "project.title": "🚀 Projet mené — Cluster Proxmox & Ceph",
        "project.intro": "J'ai conçu et mis en place une infrastructure de virtualisation en haute disponibilité, basée sur Proxmox VE avec du stockage distribué Ceph, répartie sur trois nœuds physiques.",
        "project.badge": "🏗️ Infrastructure",
        "project.step1.title": "Préparation des nœuds",
        "project.step1.desc": "Installation de Proxmox VE sur trois serveurs physiques, configuration réseau (bridge, VLAN de management, réseau Ceph dédié) et durcissement système.",
        "project.step2.title": "Création du cluster Proxmox",
        "project.step2.desc": "Initialisation du cluster sur le nœud principal, jonction des deux autres nœuds, vérification du quorum et de la synchronisation des configurations.",
        "project.step3.title": "Déploiement de Ceph via cephadm",
        "project.step3.desc": "Bootstrap du cluster Ceph, ajout des OSD (disques), configuration des monitors et managers sur chaque nœud, et création des pools de stockage.",
        "project.step4.title": "Tests & validation",
        "project.step4.desc": "Migration à chaud de VM entre les nœuds, tests de résilience (coupure d'un nœud), mesure des performances I/O et documentation complète de l'architecture.",
        "project.result.label": "Résultat :",
        "project.result.text": "Infrastructure opérationnelle en haute disponibilité avec stockage redondant, capable de supporter la perte d'un nœud sans interruption de service.",
        // FOOTER
        "footer.desc": "Étudiant en BTS SIO option SISR. Passionné par l'administration système, la cybersécurité et les infrastructures réseau.",
        "footer.rights": "© 2026 Brieuc Métairie – Portfolio",
        "404.title": "404",
        "404.msg": "Oups ! La page que vous cherchez n'existe pas ou a été déplacée.",
        "404.back": "Retour à l'accueil"
    },
    en: {
        // NAV
        "nav.accueil": "Home",
        "nav.activites": "Projects",
        "nav.entreprise": "Career",
        "nav.veille": "Blog & Watch",
        "nav.contact": "Contact Me",
        "nav.links": "Quick Links",
        "nav.social": "Socials",
        "nav.mentions": "Legal Notice",
        "nav.confidentialite": "Privacy Policy",
        // HERO
        "hero.subtitle": "BTS SIO Student – SISR Option",
        "hero.title": "Future System & Network Administrator",
        "hero.desc": "Currently in my second year of BTS SIO (SISR option), I'm training in <strong>infrastructure management</strong> and <strong>cybersecurity</strong>. This portfolio documents my journey, projects and skills.",
        "hero.cta": "View My Projects",
        // SECTIONS - INDEX
        "section.skills": "Skills",
        "index.option.sisr.title": "SISR Option",
        "index.option.sisr.full": "Infrastructure, Systems and Network Solutions",
        "index.option.sisr.desc": "Windows and Linux server administration, network management (VLAN, routing, Wi-Fi), security (firewall, VPN, backups), virtualization (Proxmox, VMware) and infrastructure monitoring.",
        "index.option.slam.title": "SLAM Option",
        "index.option.slam.full": "Software Solutions and Business Applications",
        "index.option.slam.desc": "Web and mobile application development, database design, object-oriented programming, software project management and testing.",
        "index.option.chosen": "✅ My choice",
        "index.option.why_sisr": "<strong>Why SISR?</strong> What drew me in is the hands-on work: setting up servers, configuring networks, securing infrastructure and solving problems in real time. SISR matches the career I want to build.",
        "index.skills.intro": "The BTS SIO offers two specializations. I chose <strong>SISR (Infrastructure, Systems and Network Solutions)</strong> because it matches what I want to do: work with servers, networks, security and daily operations. We learn to deploy services (Active Directory, DNS, DHCP, virtualization...), monitor them, and handle incidents properly.",
        "index.skills.list1": "Workstation setup and configuration (OS deployment, drivers, business tools)",
        "index.skills.list2": "Server and network administration (backups, monitoring, VLAN, DHCP/DNS)",
        "index.skills.list3": "System and access security (permissions, encryption, updates, firewall)",
        "index.skills.list4": "User support, technical documentation and procedure writing",
        "skills.os": "Systems",
        "skills.net": "Networking",
        "skills.sec": "Security",
        "skills.tools": "Tools & Soft Skills",
        "section.projects": "Latest Projects",
        "index.projects.title": "Recent Projects",
        "index.projects.intro": "Here are some of the projects I've completed, both during my training and on my own. They cover system administration, networking and virtualization.",
        "index.projects.btn": "📂 View all projects",
        "index.school.title": "My School — Faculté des Métiers de l'Essonne",
        "index.school.text": "I'm preparing my BTS SIO at <strong>FDME</strong> through a work-study program. This format lets me bridge what I learn in class with what I practice at work. That's how I learn fastest: by applying knowledge directly in the field.",
        "index.school.btn": "Discover FDME",
        "index.cv.title": "My Resume",
        "index.cv.text": "My resume includes my background, technical skills and the missions I've completed in the workplace. It's regularly updated.",
        "index.cv.btn": "📄 Download Resume (PDF)",
        "section.contact": "Let's Get in Touch",
        // ENTREPRISE
        "company.title": "My Work-Study at Althec",
        "company.intro_title": "Company Overview",
        "company.desc": "<strong>ALTHEC Sécurité Systèmes</strong> is an SME specializing in electronic security. It supports clients through every stage: needs assessment, solution selection, on-site installation, and long-term maintenance. The direct client relationship allows for quick adaptation.",
        "company.details.social": "Company Name:",
        "company.details.legal": "Legal Form:",
        "company.details.creation": "Creation Date:",
        "company.details.hq": "Headquarters:",
        "company.details.sector": "Sector:",
        "company.details.workforce": "Workforce:",
        "company.details.zone": "Zone:",
        "company.details.clients": "Clientele:",
        "company.details.turnover": "Turnover:",
        "company.activity.title": "Main Activity",
        "company.activity.text": "Althec designs and installs security systems tailored to each site: IP surveillance cameras, alarm systems, badge-based access control, intercoms. Once deployed, the company provides ongoing support through preventive and corrective maintenance.",
        "company.services.title": "Service Offer",
        "company.services.list1.title": "Study & Consulting:",
        "company.services.list1.desc": "risk analysis, technical recommendations, cost estimation",
        "company.services.list2.title": "Installation:",
        "company.services.list2.desc": "cabling, hardware setup, configuration and commissioning",
        "company.services.list3.title": "Network Integration:",
        "company.services.list3.desc": "IP addressing, secure remote access, monitoring",
        "company.services.list4.title": "Maintenance:",
        "company.services.list4.desc": "preventive and corrective interventions, technical support",
        // MISSIONS
        "missions.title": "🎯 My Missions",
        "missions.intro": "During my work-study at Althec, I worked on two main areas that helped me grow my hands-on technical skills.",
        "missions.network.title": "Network Configuration",
        "missions.network.desc": "I helped set up and deploy network equipment at client sites: switches, routers, NVRs (network video recorders) and IP cameras. This included VLAN configuration, IP addressing, firewall rules and secure remote access setup.",
        "missions.network.list1": "IP configuration of cameras and NVRs on client networks",
        "missions.network.list2": "Switch configuration (VLAN, trunk, PoE)",
        "missions.network.list3": "Secure remote access setup (VPN)",
        "missions.network.list4": "Connectivity testing and on-site troubleshooting",
        "missions.support.title": "Client Technical Support",
        "missions.support.desc": "I provided phone and on-site support to help clients resolve issues with their security systems. This involved fault diagnosis, corrective interventions, and writing service reports.",
        "missions.support.list1": "Remote incident diagnosis and resolution",
        "missions.support.list2": "On-site corrective interventions",
        "missions.support.list3": "Writing service reports",
        "missions.support.list4": "Training users on deployed tools",
        // PROJECT
        "project.title": "🚀 Project Led — Proxmox & Ceph Cluster",
        "project.intro": "I designed and deployed a high-availability virtualization infrastructure based on Proxmox VE with distributed Ceph storage, spread across three physical nodes.",
        "project.badge": "🏗️ Infrastructure",
        "project.step1.title": "Node Preparation",
        "project.step1.desc": "Proxmox VE installation on three physical servers, network configuration (bridge, management VLAN, dedicated Ceph network) and system hardening.",
        "project.step2.title": "Proxmox Cluster Creation",
        "project.step2.desc": "Cluster initialization on the main node, joining the two other nodes, quorum verification and configuration synchronization check.",
        "project.step3.title": "Ceph Deployment via cephadm",
        "project.step3.desc": "Ceph cluster bootstrap, OSD (disk) addition, monitor and manager configuration on each node, and storage pool creation.",
        "project.step4.title": "Testing & Validation",
        "project.step4.desc": "Live VM migration between nodes, resilience testing (node shutdown), I/O performance measurement and full architecture documentation.",
        "project.result.label": "Result:",
        "project.result.text": "Fully operational high-availability infrastructure with redundant storage, able to handle a node failure without service interruption.",
        // ACTIVITES - GENERAL
        "projects.title": "Projects",
        "projects.search_placeholder": "Search a project (e.g. MediaWiki, GLPI, Plex, Pi-hole)...",
        "projects.filter_all": "All",
        "projects.filter_network": "Network",
        "projects.filter_security": "Security",
        "projects.filter_system": "System",
        "projects.filter_web": "Web",
        "projects.intro": "Here I present my training projects and those I built independently at home. Each one addresses a real need or a desire to explore a subject further.",
        "projects.school_title": "📘 Training Projects",
        "projects.personal_title": "🛠️ Personal Projects",
        "projects.goal_label": "Goal:",
        "projects.env_label": "Environment:",
        "projects.material_label": "Hardware:",
        "projects.result_label": "Result:",
        "projects.btn_detail": "View Details →",
        "projects.btn_pdf": "📄 PDF Doc",
        // ACTIVITES - CARDS
        "projects.mediawiki.title": "MediaWiki on Windows",
        "projects.mediawiki.goal": "deploy an internal wiki to centralize technical procedures and operational documentation.",
        "projects.mediawiki.list1": "XAMPP installation and configuration",
        "projects.mediawiki.list2": "<code>mediawiki</code> database creation via phpMyAdmin",
        "projects.mediawiki.list3": "Deployment in <code>C:\\xampp\\htdocs\\mediawiki</code>",
        "projects.mediawiki.list4": "Setup wizard + extensions (VisualEditor)",
        "projects.mediawiki.list5": "SQL backups and images directory setup",
        "projects.glpi.title": "GLPI on Windows",
        "projects.glpi.goal": "set up a helpdesk and IT asset management platform.",
        "projects.glpi.list1": "Web stack installation (Apache / PHP / MariaDB)",
        "projects.glpi.list2": "<code>glpi</code> database creation via phpMyAdmin",
        "projects.glpi.list3": "Deployment in <code>C:\\xampp\\htdocs\\glpi</code>",
        "projects.glpi.list4": "Profiles, entities and SLA configuration",
        "projects.glpi.list5": "Automated inventory with FusionInventory",
        "projects.plex.title": "Plex Server on NAS",
        "projects.plex.goal": "set up a media server to centralize and stream content at home.",
        "projects.plex.list1": "Plex Media Server deployment via Docker",
        "projects.plex.list2": "Persistent volume configuration",
        "projects.plex.list3": "Library organization (Movies / TV Shows / Music)",
        "projects.plex.list4": "Multi-device access (TV, mobile, PC)",
        "projects.plex.list5": "Hardware transcoding enabled",
        "projects.plex.result": "stable server accessible from all household devices.",
        "projects.pihole.title": "Pi-hole on Raspberry Pi",
        "projects.pihole.goal": "filter ads and trackers at DNS level for the entire home network.",
        "projects.pihole.list1": "Raspberry Pi setup (OS, SSH, updates)",
        "projects.pihole.list2": "Pi-hole installation and DNS configuration",
        "projects.pihole.list3": "Router DNS redirected to Pi-hole",
        "projects.pihole.list4": "Blocklists added (ads, tracking, malware)",
        "projects.pihole.list5": "Monitoring via web dashboard",
        "projects.pihole.list6": "Configuration backup and static IP assignment",
        "projects.pihole.result": "cleaner browsing and better-protected network.",
        "projects.vpn.title": "VPN Server on Raspberry Pi",
        "projects.vpn.goal": "securely access my home network from outside.",
        "projects.vpn.list1": "Raspberry Pi hardening (SSH, firewall, fail2ban)",
        "projects.vpn.list2": "VPN server deployment (WireGuard)",
        "projects.vpn.list3": "Client profile generation (PC and mobile)",
        "projects.vpn.list4": "Port forwarding + DDNS on router",
        "projects.vpn.list5": "Firewall rules to restrict access",
        "projects.vpn.list6": "External testing and documentation writing",
        "projects.vpn.result": "working, encrypted and documented remote access.",
        "projects.restaurant.btn_site": "🌐 Visit Website",
        // VEILLE
        "blog.title": "Tech Watch",
        "blog.intro": "As part of the BTS SIO curriculum, I conduct regular tech watch on topics related to my future career: system administration, cybersecurity, and regulatory changes. Here are my articles and analyses.",
        "blog.read_more": "Read full article →",
        "blog.read_analysis": "Read analysis →",
        "blog.rss_title": "📡 RSS Feed — Real-Time News",
        "blog.analysis.title": "📝 My Article Analyses",
        "blog.analysis.intro": "I select articles related to my specialization and write personal analyses to show that I understand the real-world implications behind technical news.",
        "blog.analysis.badge": "📖 Analysis",
        "blog.analysis.summary_label": "<strong>Article summary:</strong>",
        "blog.analysis.my_analysis": "<strong>My analysis:</strong>",
        "blog.analysis1.date": "📅 Feb 10, 2026",
        "blog.analysis1.title": "The rise of passkeys: towards the end of passwords?",
        "blog.analysis1.source": "Source: IT-Connect",
        "blog.analysis1.summary": "Passkeys are gradually replacing traditional passwords. Based on the FIDO2/WebAuthn standard, they use biometrics or a local PIN to authenticate users without ever sending a secret to the server. Google, Apple and Microsoft now integrate them natively into their platforms.",
        "blog.analysis1.analysis": "As a future system administrator, this evolution directly concerns me. Passwords are often the weakest security link: phishing, reuse, weak complexity. Passkeys solve these issues by removing the shared secret between client and server. But in an enterprise context, deployment raises practical questions: is it compatible with existing Active Directory? How do you manage it centrally? How do you train users? This is a technology I'm keeping a close eye on.",
        "blog.analysis2.date": "📅 Jan 28, 2026",
        "blog.analysis2.title": "NIS 2: the new European cybersecurity directive",
        "blog.analysis2.source": "Source: ANSSI",
        "blog.analysis2.summary": "The NIS 2 directive, effective since October 2024, significantly expands the number of organizations subject to cybersecurity obligations in Europe. It mandates risk management, incident reporting and governance measures for thousands of additional entities, including SMEs and local authorities.",
        "blog.analysis2.analysis": "NIS 2 will change the daily work of system administrators. Companies will need to strengthen their backup, monitoring and incident response policies. For a SISR technician like me, that means mastering detection tools (SIEM, IDS/IPS), properly documenting procedures and knowing how to respond in a crisis. It's a regulatory framework that makes our skills even more valuable.",
        "blog.stack_title": "📚 My Watch Stack",
        "blog.cat_law": "Legislation & Law",
        "blog.cat_ia": "AI & Sovereignty",
        "blog.article1.date": "📅 Nov 15, 2024",
        "blog.article1.source": "Source: IT-Connect",
        "blog.article1.title": "Windows Server 2025: what's new for admins?",
        "blog.article1.desc": "Microsoft is preparing Windows Server 2025. Enhanced Active Directory, Hotpatching, better NVMe performance... An overview of the features that will impact daily system administration.",
        "blog.article2.date": "📅 Oct 02, 2024",
        "blog.article2.source": "Source: CNIL",
        "blog.article2.title": "GDPR: what's the economic impact after 6 years?",
        "blog.article2.desc": "Is privacy compliance holding companies back or driving them forward? A look at the CNIL's findings and the real-world impacts for IT departments.",
        "blog.article3.date": "📅 Sept 28, 2024",
        "blog.article3.source": "Source: ZDNet",
        "blog.article3.title": "Digital sovereignty: the open-source AI challenge",
        "blog.article3.desc": "With Mistral AI and Hugging Face, France has cards to play against US tech giants. Open-source AI is a major issue for European technological independence.",
        // FOOTER
        "footer.desc": "BTS SIO student, SISR option. Passionate about system administration, cybersecurity and network infrastructure.",
        "footer.rights": "© 2026 Brieuc Métairie – Portfolio",
        "404.title": "404",
        "404.msg": "Oops! The page you're looking for doesn't exist or has been moved.",
        "404.back": "Back to Home"
    }
};
