const translations = {
    fr: {
        // NAV
        "nav.accueil": "Accueil",
        "nav.activites": "Activités",
        "nav.entreprise": "Entreprise",
        "nav.veille": "Veille",
        "nav.contact": "Me contacter",
        "nav.links": "Liens Rapides",
        "nav.social": "Réseaux",
        "nav.mentions": "Mentions Légales",
        "nav.confidentialite": "Confidentialité",
        // HERO
        "hero.subtitle": "Étudiant en BTS SIO – option SISR",
        "hero.title": "Administration Système, Réseau & Cybersécurité",
        "hero.desc": "Actuellement en deuxième année de BTS SIO (Services Informatiques aux Organisations) avec une spécialisation en SISR (Solutions d'Infrastructure, Systèmes et Réseaux). Passionné par les rouages de l'informatique d'entreprise, mon objectif est de concevoir, déployer et sécuriser des infrastructures robustes. J'apprécie particulièrement l'aspect concret du métier : de l'installation de serveurs et du brassage réseau jusqu'à la mise en place de politiques de sécurité avancées, chaque projet est pour moi l'occasion de relever un nouveau défi technique et de garantir une haute disponibilité des services.",
        "hero.cta": "Découvrir mes réalisations professionnelles",
        // SECTIONS - INDEX
        "section.skills": "Cartographie de mes Compétences",
        "index.option.sisr.title": "Spécialisation SISR",
        "index.option.sisr.full": "Solutions d'Infrastructure, Systèmes et Réseaux",
        "index.option.sisr.desc": "La SISR est le cœur battant de toute organisation moderne. Cette spécialisation forme à l'architecture, l'administration et la sécurisation des réseaux d'entreprise. De la gestion des serveurs physiques et virtualisés (Windows Server, Linux) à la configuration des équipements actifs (commutateurs, routeurs, pare-feux), l'objectif est d'assurer une infrastructure performante, résiliente et sécurisée face aux menaces actuelles.",
        "index.option.slam.title": "L'alternative SLAM",
        "index.option.slam.full": "Solutions Logicielles et Applications Métiers",
        "index.option.slam.desc": "Le parcours SLAM est orienté vers la création logicielle : développement d'applications métiers (web, mobile, lourdes), modélisation et gestion de bases de données, maîtrise de la programmation orientée objet et intégration des processus agiles dans le cycle de vie du développement.",
        "index.option.chosen": "✅ Mon parcours choisi",
        "index.option.why_sisr": "<strong>Pourquoi avoir choisi la spécialité SISR ?</strong> Mon choix s'est naturellement porté vers l'infrastructure car je suis fasciné par la dimension matérielle et architecturale de l'informatique. Prendre une baie vide, la câbler logiquement, configurer les équipements et voir l'ensemble du réseau s'animer pour fournir un service indispensable à une entreprise est extrêmement gratifiant. J'aime comprendre comment les paquets transitent, comment isoler des menaces via des VLANs, et surtout, j'ai besoin d'avoir cette vision globale et de toucher concrètement aux fondations mêmes des systèmes d'information.",
        "index.skills.intro": "Dans le cadre de mon BTS SIO option SISR, j'ai acquis de solides compétences techniques et méthodologiques me permettant d'intervenir sur l'ensemble du cycle de vie d'une infrastructure. De l'audit initial à la recette finale, en passant par le maquettage et le déploiement. Voici les piliers de mon expertise :",
        "index.skills.list1": "<strong>Intégration et Support :</strong> Préparation, mastérisation et déploiement de parcs informatiques complets. Résolution d'incidents (helpdesk) de niveaux 1 et 2 pour assurer un maintien en condition opérationnelle continu.",
        "index.skills.list2": "<strong>Administration Système & Réseau :</strong> Déploiement et gestion centralisée des services d'infrastructures critiques (Active Directory, DNS, DHCP, GPO). Configuration experte des équipements actifs (Switchs, Routeurs Cisco/TP-Link) et segmentation réseau.",
        "index.skills.list3": "<strong>Cybersécurité :</strong> Protection des données sensibles et contrôle d'accès. Mise en œuvre de politiques de moindres privilèges, de pare-feux (filtrage MAC, ACLs), et de connexions distantes sécurisées (VPN, certificats numériques).",
        "index.skills.list4": "<strong>Documentation & Méthodologie :</strong> Rédaction de guides d'exploitation, de procédures techniques et création de schémas topologiques clairs pour faciliter la passation et garantir la traçabilité des interventions.",
        "skills.os": "Administration Systèmes",
        "skills.net": "Architecture Réseaux",
        "skills.sec": "Cybersécurité",
        "skills.tools": "Outils Transverses",
        "section.projects": "Mes Réalisations Récentes",
        "index.projects.title": "Panorama des Projets",
        "index.projects.intro": "Bienvenue dans mon espace laboratoire. Vous y trouverez un aperçu exhaustif de mes réalisations académiques et professionnelles, mais également des projets d'initiative personnelle. Ces derniers me permettent d'explorer des technologies hors cursus, d'expérimenter en condition réelle et de construire mon propre écosystème de services (Cloud personnel, supervision, domotique).",
        "index.projects.btn": "📂 Explorer l'intégralité de mon portfolio",
        "index.school.title": "Mon établissement de formation — Faculté des Métiers de l'Essonne (FDME)",
        "index.school.text": "Je poursuis actuellement mon cursus en apprentissage au sein de la <strong>FDME</strong> (Faculté des Métiers de l'Essonne). Le format de l'alternance offre un équilibre parfait et une maturation accélérée : les acquis théoriques abordés en cours sont directement confrontés à la réalité du terrain et aux exigences professionnelles en entreprise. C'est, selon moi, la voie royale pour développer une expertise technique fiable et un savoir-être professionnel inestimable.",
        "index.school.btn": "Découvrir le campus FDME",
        "index.option.title": "Les fondations : Le BTS SIO",
        "index.future_project.title": "Perspective d'avenir : Bachelor Chef de Projet Informatique (CPI)",
        "index.future_project.text": "Dans la continuité logique de mon BTS SIO, j'ambitionne de poursuivre mes études vers un Bachelor CPI (Concepteur/Chef de Projets Informatiques). Cette formation bac+3 me permettra de transcender mon profil technique actuel pour développer une véritable capacité de chefferie de projet. L'objectif est d'acquérir les compétences nécessaires pour auditer des infrastructures existantes, proposer des solutions évolutives chiffrées (budget, planning, risques), et piloter des projets de migration complexes avec une vision stratégique et managériale du système d'information.",
        "index.cv_and_skills.title": "Parcours & Compétences Techniques",
        "index.cv.title": "Curriculum Vitae détaillé",
        "index.cv.text": "Mon Curriculum Vitae retrace de manière synthétique mon évolution académique, mon exposition professionnelle au travers de mes missions en entreprise, ainsi qu'une vue consolidée de mon bagage technologique. Celui-ci est maintenu rigoureusement à jour pour refléter mes dernières certifications et accomplissements.",
        "index.cv.btn": "📄 Télécharger mon CV complet (PDF)",
        "section.contact": "Me contacter pour de futurs projets",
        // ENTREPRISE
        "company.title": "Mon expérience professionnelle chez ALTHEC Sécurité",
        "company.intro_title": "Présentation de l'entreprise d'accueil",
        "company.desc": "J'effectue mon alternance au sein d'<strong>ALTHEC Sécurité Systèmes</strong>, une PME spécialisée de pointe en ingénierie de sûreté électronique et en réseaux de communication pour les bâtiments professionnels, industriels et d'habitation. Reconnue pour son expertise de terrain, l'équipe technique d'ALTHEC se distingue par sa capacité à proposer un accompagnement intégral (Turnkey solutions) à forte valeur ajoutée : depuis l'audit initial des locaux et la validation de la topologie réseau, jusqu'au déploiement physique du matériel, sa configuration sur-mesure, et la supervision opérationnelle à long terme.",
        "company.details.social": "Raison sociale :",
        "company.details.legal": "Forme juridique :",
        "company.details.creation": "Date de création :",
        "company.details.hq": "Siège social :",
        "company.details.sector": "Secteur :",
        "company.details.workforce": "Effectif :",
        "company.details.zone": "Zone géographique :",
        "company.details.clients": "Typologie clientèle :",
        "company.details.turnover": "Chiffre d'affaires :",
        "company.activity.title": "Cœur de métier et savoir-faire",
        "company.activity.text": "ALTHEC conçoit, intègre et maintient des systèmes connectés critiques protégeant les biens et les personnes : architectures de vidéosurveillance IP haute définition, détection intrusion périmétrique, contrôle d'accès biométrique et RFID, ainsi que les réseaux supportant ces flux de données. Au-delà du déploiement initial, l'entreprise garantit la pérennité de ces environnements à travers des contrats de maintenance préventive (visites de contrôle) et corrective (interventions d'urgence).",
        "company.services.title": "Panorama de l'offre de services",
        "company.services.list1.title": "Missions d'Audit & Ingénierie-Conseil :",
        "company.services.list1.desc": "Évaluation granulaire des vulnérabilités d'un site, préconisations architecturales (choix des technologies, dimensionnement réseau) et élaboration de cahiers des charges financiers (chiffrage précis).",
        "company.services.list2.title": "Déploiement Physique & Intégration :",
        "company.services.list2.desc": "Réalisation du câblage structuré (cuivre, fibre optique), installation physique des équipements terminaux et de la baie de brassage, raccordements électriques sécurisés.",
        "company.services.list3.title": "Configuration Réseau & Sécurité Appliquée :",
        "company.services.list3.desc": "Paramétrage actif : adressage IP, création de VLANs dédiés à la sûreté, mise en place de flux distants sécurisés (VPN), et configuration des logiciels de supervision (VMS).",
        "company.services.list4.title": "Maintien en Condition Opérationnelle (MCO) :",
        "company.services.list4.desc": "Diagnostic approfondi et résolution de pannes (support de niveau 1 à 3), remplacements matériels préventifs, mises à jour des micro-logiciels (firmwares) et accompagnement des utilisateurs.",
        // ACTIVITES - GENERAL
        "projects.title": "Catalogue des Activités et Projets",
        "projects.search_placeholder": "Rechercher par technologie ou projet (ex: Active Directory, GLPI, Docker, Réseau)...",
        "projects.filter_all": "Tous les projets",
        "projects.filter_network": "Infrastructure Réseau",
        "projects.filter_security": "Cybersécurité",
        "projects.filter_system": "Administration Système",
        "projects.filter_web": "Développement & Web",
        "projects.intro": "Cette section regroupe un panel représentatif de mes travaux. Vous y trouverez d'une part les projets structurants menés en formation (validant mes acquis académiques) et en entreprise, et d'autre part mes « laboratoires » personnels montés en autodidacte pour éprouver de nouvelles technologies, notamment dans l'écosystème open-source.",
        "projects.school_title": "📘 Projets de formation académique",
        "projects.pro_title": "💼 Réalisations en milieu professionnel",
        "projects.personal_title": "🛠️ Laboratoires et Initiatives personnelles",
        "projects.goal_label": "Objectif du projet :",
        "projects.env_label": "Environnement technique :",
        "projects.material_label": "Ressources matérielles :",
        "projects.result_label": "Résultat final :",
        "projects.content_label": "Détail du livrable :",
        "projects.skills_label": "Compétences clés mobilisées :",
        "skill.windows": "Administration Windows Server",
        "skill.linux": "Administration GNU/Linux",
        "skill.network": "Ingénierie Réseau",
        "skill.security": "Cybersécurité",
        "skill.helpdesk": "Support IT & Gestion Parc",
        "skill.docker": "Conteneurisation (Docker)",
        "skill.db": "Gestion Bases de Données",
        "skill.web": "Stack Web & Déploiement",
        "skill.doc": "Documentation Technique",
        "skill.hardware": "Maintenance Matérielle",
        "skill.ad": "Active Directory (AD DS)",
        "skill.m365": "Administration Microsoft 365",
        "skill.scripting": "Automatisation / Scripting",
        "skill.vpn": "Accès Distants & VPN",
        "skill.dns": "Architecture DNS",
        "projects.btn_detail": "Consulter l'étude de cas détaillée →",
        "projects.btn_pdf": "📄 Documentation associée (PDF)",
        // ACTIVITES - CARDS
        "projects.mediawiki.title": "Déploiement MediaWiki sous Windows",
        "projects.mediawiki.goal": "Déployer une base de connaissances pérenne, scalable et collaborative afin de centraliser l'expertise technique, standardiser les procédures d'intervention et réduire considérablement le temps de recherche documentaire des équipes IT.",
        "projects.mediawiki.list1": "Préparation du serveur hébergeur et installation de la stack WAMP (XAMPP).",
        "projects.mediawiki.list2": "Création sécurisée de la base de données <code>mediawiki</code> via phpMyAdmin (gestion des utilisateurs et privilèges).",
        "projects.mediawiki.list3": "Déploiement scrupuleux des sources MediaWiki dans le répertoire <code>C:\\xampp\\htdocs\\mediawiki</code>.",
        "projects.mediawiki.list4": "Initialisation de l'instance via l'assistant de configuration web et intégration de l'extension 'VisualEditor' pour faciliter la contribution.",
        "projects.mediawiki.list5": "Structuration d'une politique de sauvegarde automatisée (dumps SQL réguliers) et protection des répertoires sensibles.",
        "projects.glpi.title": "Gestion de Parc & Helpdesk via GLPI",
        "projects.glpi.goal": "Mettre en œuvre une solution ITSM complète (GLPI) pour répertorier l'exhaustivité des actifs matériels et logiciels, tout en rationalisant le support utilisateur via un portail de gestion des incidents (Ticketing) structuré par les normes ITIL.",
        "projects.glpi.list1": "Installation d'un environnement Web complet (Apache 2.4 / PHP 8 / MariaDB) sous Windows.",
        "projects.glpi.list2": "Déploiement de la base de données spécifique <code>glpi</code> et ajustement des paramètres de performance dans <code>php.ini</code>.",
        "projects.glpi.list3": "Exécution de la routine d'installation de GLPI dans un dossier racine dédié (<code>htdocs/glpi</code>).",
        "projects.glpi.list4": "Paramétrage organisationnel de GLPI : création d'entités métiers, de groupes de techniciens, et définition stricte des profils et des droits d'accès.",
        "projects.glpi.list5": "Automatisation complète de l'inventaire matériel grâce à l'extension FusionInventory et au déploiement des agents de remontée sur les terminaux clients.",
        "projects.plex.title": "Serveur Multimédia Plex sur NAS",
        "projects.plex.goal": "Construire un centre multimédia privé centralisé, hautement disponible, capable de diffuser des contenus volumineux vers tout type d'appareil (PC, Smart TV, mobiles), en s'affranchissant des contraintes de stockage local et des abonnements VOD.",
        "projects.plex.list1": "Mise en place de l'infrastructure logicielle via Docker sur un NAS Synology dédié.",
        "projects.plex.list2": "Configuration avancée des volumes persistants pour dissocier les médias des transcodages temporaires.",
        "projects.plex.list3": "Organisation structurée des métadonnées (Films, Séries, Musiques) et synchronisation via agents de scraping automatiques.",
        "projects.plex.list4": "Gestion granulaire des permissions et du partage des bibliothèques avec différents profils utilisateurs.",
        "projects.plex.list5": "Optimisation des performances avec l'activation du transcodage matériel (réduction de la charge CPU lors du streaming à distance).",
        "projects.plex.result": "Un service multimédia central robuste, capable de transcoder plusieurs flux 4K simultanément sans heurts.",
        "projects.pihole.title": "Bloqueur DNS réseau (Pi-hole)",
        "projects.pihole.goal": "Épurer le trafic réseau global en bloquant proactivement les domaines publicitaires, les trackers de données et les domaines malveillants connus, ceci au niveau DNS, protégeant ainsi silencieusement tous les appareils connectés (Smartphones, PC, IoT).",
        "projects.pihole.list1": "Préparation et sécurisation d'un Raspberry Pi (installation de l'OS headless, verrouillage SSH, mises à jour critiques).",
        "projects.pihole.list2": "Déploiement du service Pi-hole et configuration primaire de la résolution DNS ascendante.",
        "projects.pihole.list3": "Modification de la gateway DHCP (Routeur/Box) pour forcer le trafic DNS vers l'adresse IP statique du Pi-hole.",
        "projects.pihole.list4": "Importation de listes de filtrage (blocklists) agressives contre les télémetries, la pub et les malwares polymorphes.",
        "projects.pihole.list5": "Mise en place d'une routine de consultation des logs et du tableau de bord d'administration pour analyser les requêtes bloquées.",
        "projects.pihole.list6": "Configuration de l'export de logs de requêtes, sauvegarde des listes blanches/noires, et durcissement de l'IP du Raspberry.",
        "projects.pihole.result": "Un réseau assaini : suppression visuelle massive de publicités et réduction radicale des pings de pistage intrusifs.",
        "projects.vpn.title": "Accès Distant Sécurisé (VPN WireGuard)",
        "projects.vpn.goal": "Concevoir un tunnel d'accès chiffré permettant de se connecter au réseau local de l'entreprise (ou du domicile) depuis un réseau non fiable (ex: Wi-Fi public), offrant les mêmes conditions de travail et la même sécurité qu'une présence sur site.",
        "projects.vpn.list1": "Sécurisation en profondeur d'un hôte Raspberry Pi : paramétrage d'UFW (pare-feu) et installation de Fail2Ban pour contrer le bruteforce SSH.",
        "projects.vpn.list2": "Installation et paramétrage du protocole WireGuard, réputé pour sa cryptographie moderne et sa légèreté.",
        "projects.vpn.list3": "Génération de paires de clés publiques/privées cryptographiques et édition des profils pour les terminaux distants (clients Windows, macOS, terminaux Android/iOS).",
        "projects.vpn.list4": "Configuration du routage NAT (Ouverture de port UDP dédié) sur le routeur de bordure et maintien de l'accessibilité via un nom de domaine dynamique (DDNS).",
        "projects.vpn.list5": "Édition minutieuse des règles de filtrage (iptables) pour restreindre l'accès client à certains sous-réseaux spécifiques (micro-segmentation).",
        "projects.vpn.list6": "Validation de l'établissement du Handshake depuis un réseau 4G externe et rédaction du processus d'ajout de nouveaux clients.",
        "projects.vpn.result": "Un pont réseau invisible et inébranlable, offrant des débits élevés grâce à l'efficacité du protocole en espace noyau.",
        "projects.restaurant.btn_site": "🌐 Visiter le site en production",
        "projects.restaurant.title": "Développement d'un Site Vitrine (Restaurant)",
        "projects.restaurant.goal": "Réaliser une vitrine web épurée, performante et immédiatement compréhensible pour un professionnel de la restauration. L'objectif était d'abandonner les générateurs lourds au profit d'un développement ciblé garantissant un temps de chargement inférieur à 2 secondes et une excellente indexation locale.",
        "projects.restaurant.content": "Le site comprend une architecture à quatre piliers (Accueil impactant, Carte interactive, Informations logistiques, Modulaire Contact). Le design a été pensé pour maximiser la conversion (appel téléphonique direct, réservation en ligne).",
        "projects.restaurant.list1": "Conception des wireframes et maquettage UI, suivi d'une intégration stricte en HTML5, CSS3 modulaire (Variables, Grid) et JavaScript asynchrone.",
        "projects.restaurant.list2": "Intégration du concept 'Mobile-First' : le site est parfaitement proportionné des petits écrans smartphones aux moniteurs larges.",
        "projects.restaurant.list3": "Optimisations WebPerf : formats d'images modernes (WebP compressé), minification des ressources, mise en cache navigateur agressive.",
        "projects.restaurant.list4": "Développement d'un formulaire de contact dynamique protégé par un système de validation côté client, et ancrage des réseaux sociaux.",
        "projects.newsletter.title": "Développement d'un Moteur de Newsletter",
        "projects.newsletter.goal": "Doté d'un budget nul pour des licences logicielles, la directive était d'offrir à une structure associative la capacité d'arroser sa base de plus de 500 adhérents de manière fiable, sans risquer de finir dans les filtres anti-spam, tout en fournissant des métriques d'ouverture.",
        "projects.newsletter.list1": "Architecture et déploiement d'un service web backend autonome en Node.js, couplé à une base de données légère (SQLite) pour la persistance des profils.",
        "projects.newsletter.list2": "Couplage applicatif avec l'API REST de Brevo (Sendinblue) agissant comme relais SMTP de confiance pour s'assurer une haute délivrabilité.",
        "projects.newsletter.list3": "Élaboration d'une interface d'administration sécurisée permettant aux gestionnaires d'importer des contacts",
        "projects.newsletter.list4": "Déploiement en continu du conteneur applicatif sur l'hébergeur cloud Render.com, monitoré par des requêtes de Keep-Alive via UptimeRobot.",
        "projects.newsletter.list5": "Rédaction d'une documentation complète (déploiement, utilisation, sauvegarde)",
        "projects.newsletter.result": "système fonctionnel, documenté et prêt à l'emploi pour l'association, coût 0 €/mois.",
        // ACTIVITÉS PROFESSIONNELLES
        // ACTIVITÉS PROFESSIONNELLES
        "projects.support_glpi.title": "Administration Helpdesk via GLPI",
        "projects.support_glpi.goal": "Assurer un Support Utilisateur (N1/N2) proactif et tracer exhaustivement le cycle de vie des incidents matériels et logiciels via la plateforme de ticketing interne GLPI de l'entreprise.",
        "projects.support_glpi.list1": "Qualification, diagnostic à distance et résolution des tickets d'incidents (panne réseau, blocage logiciel).",
        "projects.support_glpi.list2": "Maintien de la CMDB (Base de données de gestion de configuration) : inventaire des assets, affectation du matériel.",
        "projects.support_glpi.list3": "Interventions de proximité pour l'installation physique de postes de travail et le brassage de prises.",
        "projects.support_glpi.list4": "Création et mise à jour de la base de connaissances interne (procédures de contournement, FAQ utilisateurs).",
        "projects.support_glpi.result": "Un taux de résolution au premier contact (FCR) amélioré et une parfaite traçabilité des interventions techniques pour le suivi qualité.",
        "projects.m365_ad.title": "Infogérance locale & Microsoft 365",
        "projects.m365_ad.goal": "Orchestrer l'environnement de travail hybride des collaborateurs en couplant une architecture Active Directory locale (On-Premise) à l'écosystème Cloud Microsoft 365 pour une gestion centralisée des identités et des outils collaboratifs.",
        "projects.m365_ad.list1": "Promotion d'un serveur Windows en contrôleur de domaine (AD DS) et configuration des services de base (DNS, DHCP).",
        "projects.m365_ad.list2": "Création de l'arborescence Active Directory (OU), gestion des groupes de sécurité et application de stratégies de groupe (GPO) pour durcir les postes.",
        "projects.m365_ad.list3": "Création et attribution des licences utilisateur Microsoft 365 (Exchange Online, SharePoint, paramétrage de Teams).",
        "projects.m365_ad.list4": "Mastérisation des terminaux via clés bootables Windows et intégration transparente des postes au domaine de l'entreprise.",
        "projects.m365_ad.result": "Un système d'information fluide, sécurisé par des GPOs restrictives et un environnement collaboratif Cloud pleinement opérationnel.",
        "projects.omada.title": "Supervision Réseau TP-Link Omada SDN",
        "projects.omada.goal": "Déployer et administrer une architecture réseau Software-Defined Networking (SDN) centralisée pour piloter l'ensemble de la flotte de commutation et de routage depuis une console logicielle cloud unique.",
        "projects.omada.list1": "Déploiement du contrôleur hybride Omada pour l'adoption et l'ingestion automatique des nouveaux matériels réseau sur les sites clients.",
        "projects.omada.list2": "Agrégation de liens (LACP), configuration des VLANs par port (802.1Q) pour isoler les flux VoIP, Data et Vidéosurveillance.",
        "projects.omada.list3": "Orchestration multi-sites des mises à jour de firmwares groupées pendant les fenêtres de maintenance nocturnes.",
        "projects.omada.list4": "Définition de seuils d'alertes SNMP, gestion de l'historique de rétention des logs, et diagnostics de performance réguliers.",
        "projects.omada.result": "Une observabilité réseau absolue (monitoring en temps réel), permettant une proactivité immédiate en cas de chute d'un lien uplink ou de congestion.",
        // VEILLE
        "blog.title": "Laboratoire & Veille Technologique",
        "blog.intro": "L'écosystème IT est soumis à une obsolescence rapide des compétences. L'unique parade est une veille technologique rigoureuse et continue. Pour consolider ma compréhension de l'état de l'art (Cybersécurité, Nouvelles Architectures Systèmes, Environnement Cloud), j'agrège quotidiennement mes flux via l'application <strong>Feeeeed</strong> sur mobile, en y croisant mes réseaux professionnels <strong>LinkedIn</strong> et les créateurs de contenu sur <strong>YouTube</strong>.",
        "blog.read_more": "Consulter l'article original →",
        "blog.read_analysis": "Parcourir ma note de synthèse →",
        "blog.rss_title": "📡 Flux RSS en Direct — Pulse de l'Industrie",
        "blog.analysis.title": "📝 Rétrospectives & Notes de Synthèse",
        "blog.analysis.intro": "La lecture passive est insuffisante. J'adopte une démarche de décorticage actif en rédigeant des notes de synthèse sur les publications les plus disruptives qui influencent ma vision de l'ingénierie système.",
        "blog.analysis.badge": "📖 Note de synthèse",
        "blog.analysis.summary_label": "<strong>Macro-synthèse de la publication :</strong>",
        "blog.analysis.my_analysis": "<strong>Décryptage & Impact Technique :</strong>",
        "blog.analysis4.date": "📅 10 Oct 2025",
        "blog.analysis4.title": "Les débuts de l'IA offensive : quand le phishing s'industrialise",
        "blog.analysis4.source": "Source : Zataz",
        "blog.analysis4.summary": "En octobre 2025, les premières campagnes massives de phishing générées par de l'Intelligence Artificielle ont été détectées. Ces vecteurs d'attaque, expurgés des fautes de syntaxe usuelles et contextuellement pertinents, ont démontré un taux de compromission supérieur de 30% lors d'audits Red Team. L'émergence de frameworks offensifs LLM (ex: 'FraudGPT') a drastiquement abaissé la barrière à l'entrée technologique pour les acteurs malveillants.",
        "blog.analysis4.analysis": "Cette démocratisation de l'IA offensive est un point de bascule. En tant que futur administrateur, cela m'oblige à reconsidérer la formation des utilisateurs (le maillon faible) et surtout à ériger des contrôles techniques non contournables. On ne peut plus attendre de l'utilisateur qu'il détecte un mail parfait. L'architecture de confiance doit reposer sur du filtrage anti-spam prédictif lourd, l'obligation du MFA (Authentification Multi-Facteurs) généralisé, et des stratégies conditionnelles (conditional access) basées sur la conformité de l'appareil (MDM/Intune) plutôt que sur la seule identité de l'utilisateur.",
        "blog.analysis6.date": "📅 15 Sept 2025",
        "blog.analysis6.title": "Fin 2025 : L'extinction amorcée du VPN traditionnel ?",
        "blog.analysis6.source": "Source : Le Monde Informatique",
        "blog.analysis6.summary": "L'architecture VPN sur tunnel IPSec ou SSL, octroyant un accès réseau très large une fois le périmètre franchi, accuse le poids des années face aux mouvements latéraux des ransomwares. Les DSI amorcent une migration massive vers les solutions ZTNA (Zero Trust Network Access), un modèle où le tunnel chiffré ne se connecte plus au réseau, mais atterrit directement dans le proxy de l'application spécifique requise, et ce pour chaque session individuelle. Une philosophie poussée à l'origine par le modèle BeyondCorp de Google.",
        "blog.analysis6.analysis": "C'est l'article paradigmatique qui m'a forcé à m'intéresser aux architectures Zero Trust. J'ai longtemps considéré le VPN (OpenVPN, WireGuard) comme la panacée de l'accès distant. J'ai compris l'hérésie de cette approche face au risque d'une machine compromise connectée au VPN de l'entreprise. Désormais, j'applique ce micro-ciblage même dans mes environnements de laboratoire personnels (reverse proxies segmentés couplés à des services d'authentification Authelia) pour éviter d'exposer un lien direct vers le backend de l'hyperviseur.",
        "blog.stack_title": "📚 Mes sources de ralliement",
        "blog.cat_law": "Cadre Légal & Conformité",
        "blog.cat_ia": "Déploiement & Souveraineté IA",
        "blog.article1.date": "📅 15 Nov 2024",
        "blog.article1.source": "Source : IT-Connect",
        "blog.article1.title": "Windows Server 2025 : les nouveautés pour les admins",
        "blog.article1.desc": "Microsoft prépare la relève avec Windows Server 2025. Active Directory renforcé, Hotpatching, meilleures performances NVMe… Un tour d'horizon des fonctionnalités qui vont impacter l'administration système au quotidien.",
        "blog.article2.date": "📅 02 Oct 2024",
        "blog.article2.source": "Source : CNIL",
        "blog.article2.title": "RGPD : quel bilan économique après 6 ans ?",
        "blog.article2.desc": "Le respect de la vie privée est-il un frein ou un avantage pour les entreprises ? Retour sur les constats de la CNIL et les impacts concrets pour les DSI.",
        "blog.article3.date": "📅 28 Sept 2024",
        "blog.article3.source": "Source : ZDNet",
        "blog.article3.title": "Souveraineté numérique : l'enjeu de l'IA Open Source",
        "blog.article3.desc": "Avec Mistral AI et Hugging Face, la France a des cartes à jouer face aux géants américains. L'IA open source est un enjeu majeur pour l'indépendance technologique européenne.",
        // MISSIONS
        "missions.title": "Expérience et missions en entreprise d'accueil",
        "missions.intro": "Mon cursus en alternance m'a rapidement exposé aux contraintes de la production réelle. Cette polyvalence m'a contraint à développer simultanément une rigueur dans l'exécution technique (paramétrage fin des réseaux) et une posture de conseil lors du contact direct avec les infrastructures clientes.",
        "missions.network.title": "Intégration d'infrastructures",
        "missions.network.desc": "J'ai participé au déploiement de topologies réseaux complexes depuis le génie civil jusqu'à la commutation finale. Ce niveau physique inclut le brassage des baies, la pose d'équipements de vidéosurveillance connectés (NVR) et surtout leur intégration logique et sécurisée sur le réseau existant du client.",
        "missions.network.list1": "Topologie de l'architecture IP, sous-réseautage et intégration d'équipements IoT/Caméras de bordure.",
        "missions.network.list2": "Étiquetage, brassage propre en baie et configuration de commutateurs L2/L3 (activation de VLAN dédiés et gestion de la norme Power-over-Ethernet).",
        "missions.network.list3": "Création de passerelles chiffrées (Serveurs VPN) pour garantir la maintenance prédictive à distance de manière sécurisée.",
        "missions.network.list4": "Débogage in-situ (investigation de boucles réseau, tests de réflectométrie sur liens cuivrés défectueux).",
        "missions.support.title": "Support Informatique & Maintien en Condition Opérationnelle",
        "missions.support.desc": "Agissant en qualité de technicien support pour un parc hétérogène, j'ai développé une méthodologie de diagnostic structurée (décomposition du modèle OSI lors d'un incident réseau). L'objectif était constant : minimiser le temps de coupure de service (MTTR) pour maintenir la continuité d'activité des utilisateurs finaux.",
        "missions.support.list1": "Écoute active et diagnostic de dysfonctionnements complexes (Hardware/Software) via des outils de prise en main à distance.",
        "missions.support.list2": "Interventions programmées ou en urgence ('curatif') directement sur les sites clients avec remplacement de composants (HDD, RAM, cartes réseaux).",
        "missions.support.list3": "Documentation systématique des opérations via la rédaction minutieuse de rapports d'intervention pour fiabiliser la traçabilité de nos actions.",
        "missions.support.list4": "Transfert de compétences continu : formation accélérée des clients finaux à l'exploitation de leurs nouveaux systèmes de supervision.",
        // PROJET
        "project.title": "Projet Académique Transversal — Cluster Hyperconvergé (Proxmox & Ceph)",
        "project.intro": "Dans l'optique d'éprouver mes compétences en architecture système distribuée, j'ai conceptualisé et assemblé de toutes pièces une infrastructure de virtualisation à tolérance de panne (Haute Disponibilité - HA). L'architecture matricielle exigeait de fédérer trois serveurs nus (bare-metal) pour que le crash d'un hyperviseur n'interrompe jamais le service hébergé (les machines virtuelles migrantes).",
        "project.badge": "Architecture Ingénierie & Cluster",
        "project.step1.title": "Isolation Réseau & Couche OS",
        "project.step1.desc": "Déploiement de l'hyperviseur Debian-based Proxmox VE sur trois nœuds distincts. Configuration stricte du pare-feu logiciel au niveau hôte et segmentation des flux via la création d'interfaces bridge, garantissant qu'un trafic applicatif de machine virtuelle ne congestionne jamais le backplane dédié au stockage.",
        "project.step2.title": "Fédération et Quorum (Corosync)",
        "project.step2.desc": "Agrégation des nœuds isolés en une entité clusterisée unique. Configuration fine de l'anneau de communication multicast Corosync, indispensable pour que les serveurs échangent instantanément leur statut de santé (heartbeat) et préviennent les situations critiques de 'split-brain'.",
        "project.step3.title": "Stockage Distribué Orienté Objet (SDS Ceph)",
        "project.step3.desc": "Éradication du risque de Point Individuel de Défaillance (SPOF) inhérent aux NAS / SAN traditionnels. Déploiement du système de fichiers Ceph sur l'ensemble des grappes de disques locaux du cluster. La réplication synchrone des blocs de données permet au cluster de supporter physiquement la perte matérielle totale d'un serveur sans corruption de volume.",
        "project.step4.title": "Tests de résilience",
        "project.step4.desc": "J'ai simulé des pannes (débrancher un serveur) pour vérifier que les machines virtuelles basculaient bien automatiquement sur les nœuds restants (HA).",
        "project.result.label": "Bilan :",
        "project.result.text": "J'ai réussi à obtenir une infrastructure stable et redondante. J'ai beaucoup appris sur le fonctionnement du stockage distribué et la gestion de crise en cas de panne.",
        // FOOTER
        "footer.desc": "Étudiant en BTS SIO option SISR. Passionné par l'administration système, la cybersécurité et les infrastructures réseau.",
        "footer.rights": "© 2026 Brieuc Métairie – Portfolio",
        "404.title": "404",
        "404.msg": "Oups ! La page que vous cherchez n'existe pas ou a été déplacée.",
        "404.back": "Retour à l'accueil"
    },
    en: {
        // NAV
        "nav.accueil": "Home",
        "nav.activites": "Projects",
        "nav.entreprise": "Career",
        "nav.veille": "Blog & Watch",
        "nav.contact": "Contact Me",
        "nav.links": "Quick Links",
        "nav.social": "Socials",
        "nav.mentions": "Legal Notice",
        "nav.confidentialite": "Privacy Policy",
        // HERO
        "hero.subtitle": "BTS SIO Student – SISR Specialization",
        "hero.title": "Systems, Network & Cloud Engineer",
        "hero.desc": "Currently in my 2nd year of BTS SIO, I design, deploy, and secure robust IT infrastructures. My passion lies in the core of IT: from racking bare-metal servers and optical cabling to orchestrating high-availability services and defending the perimeter.",
        "hero.cta": "Explore my portfolio",
        // SECTIONS - INDEX
        "section.skills": "Core Competencies",
        "index.option.sisr.title": "SISR Specialization",
        "index.option.sisr.full": "Infrastructure, Systems and Network Solutions",
        "index.option.sisr.desc": "The architectural choice: bare-metal servers, routed networks, and cybersecurity. This is where the foundation of an enterprise is built to be resilient, highly available, and secure against modern threats.",
        "index.option.slam.title": "SLAM Specialization",
        "index.option.slam.full": "Software Solutions and Business Applications",
        "index.option.slam.desc": "Focuses on full-stack web and mobile development, complex database design, object-oriented programming paradigms, and agile project management.",
        "index.option.chosen": "✅ My career path",
        "index.option.why_sisr": "<strong>Why SISR?</strong> Because I am driven by the physical and architectural aspects of IT. Designing a secure network topology, configuring enterprise-grade firewalls, or deploying a virtualization cluster... I need to interact with the underlying infrastructure that powers everything else.",
        "index.skills.intro": "The BTS SIO degree offers two distinct paths. I chose <strong>SISR</strong> to master the core engines of IT systems. The curriculum dives deep into server administration, network engineering, and cybersecurity. We train to build scalable architectures (Active Directory forests, DNS hierarchies, Hypervisors) and strictly secure them.",
        "index.skills.list1": "Mastering the deployment and hardening of end-user endpoints (OS imaging, MDM, GPOs).",
        "index.skills.list2": "Architecting and managing scalable server environments and complex routed networks.",
        "index.skills.list3": "Enforcing data protection and access control (Next-Gen Firewalls, IAM, cryptography).",
        "index.skills.list4": "Providing advanced technical support (Tier 2/3) and writing exhaustive IT documentation.",
        "skills.os": "Systems Admin",
        "skills.net": "Network Engineering",
        "skills.sec": "Cybersecurity",
        "skills.tools": "Tooling & Methods",
        "section.projects": "Showcase & Portfolio",
        "index.projects.title": "Recent Deployments & Labs",
        "index.projects.intro": "Welcome to my technological sandbox. Here, you'll discover milestones from my academic journey, major projects deployed in a corporate environment, as well as personal home-lab initiatives driven by curiosity and the open-source philosophy.",
        "index.projects.btn": "📂 Browse complete portfolio",
        "index.school.title": "Academic Background — Faculté des Métiers de l'Essonne",
        "index.school.text": "I am completing my degree as a work-study apprentice at <strong>FDME</strong>. This dual-track format is incredibly demanding but highly rewarding: theoretical networking and systems concepts learned in class are immediately challenged and applied in a real-world corporate production environment.",
        "index.school.btn": "Learn more about FDME",
        "index.option.title": "Academic Trajectory",
        "index.future_project.title": "Future Ambition: Bachelor's Degree in IT Project Design (CPI)",
        "index.future_project.text": "Following my BTS SIO graduation, I am committed to pursuing a Bachelor's Degree in IT Project Design (Concepteur de Projets Informatiques). This step is crucial to elevate my skills from technical implementation to high-level architectural design, IT project management, and strategic IT governance.",
        "index.cv_and_skills.title": "Professional Resume & Skill Matrix",
        "index.cv.title": "Curriculum Vitae",
        "index.cv.text": "My CV provides a structured overview of my academic progression, validated technical certifications, and concrete enterprise experience. It acts as a snapshot of my operational capabilities.",
        "index.cv.btn": "📄 Download CV (English PDF)",
        "section.contact": "Initiate a Conversation",
        // ENTREPRISE
        "company.title": "Corporate Work-Study at Althec",
        "company.intro_title": "Enterprise Overview",
        "company.desc": "<strong>ALTHEC Sécurité Systèmes</strong> is an agile SME acting as a premier integrator of physical electronic security and network infrastructures for B2B clients. The company handles the entire lifecycle of critical installations: from auditing and risk assessment to active deployment and SLA-driven maintenance.",
        "company.details.social": "Corporate Name:",
        "company.details.legal": "Legal Entity Form:",
        "company.details.creation": "Founded In:",
        "company.details.hq": "Headquarters Location:",
        "company.details.sector": "Industry Sector:",
        "company.details.workforce": "Active Workforce:",
        "company.details.zone": "Operational Zone:",
        "company.details.clients": "Client Typology:",
        "company.details.turnover": "Annual Revenue:",
        "company.activity.title": "Core Business & Expertise",
        "company.activity.text": "ALTHEC engineers, integrates, and maintains critical connected systems designed to protect assets and personnel: high-definition IP video surveillance architectures, perimeter intrusion detection, biometric and RFID access control, and the underlying network layers supporting these data streams. Beyond initial deployment, the company ensures system longevity through comprehensive preventive and corrective maintenance contracts.",
        "company.services.title": "Global Service Offer",
        "company.services.list1.title": "Audit & Engineering Consulting:",
        "company.services.list1.desc": "granular site vulnerability assessment, architectural recommendations (technology stack, network sizing), and financial scoping.",
        "company.services.list2.title": "Physical Deployment & Integration:",
        "company.services.list2.desc": "structured cabling (copper, fiber optics), physical installation of terminal endpoint hardware and server racks, secure electrical connections.",
        "company.services.list3.title": "Network Config & Applied Security:",
        "company.services.list3.desc": "active provisioning: IP addressing, security VLAN segregation, secure remote tunneling (VPN), and VMS software configuration.",
        "company.services.list4.title": "Operational Maintenance (MCO):",
        "company.services.list4.desc": "in-depth diagnostics and incident resolution (Tier 1 to 3 support), preventive hardware replacements, firmware patching, and end-user onboarding.",
        // MISSIONS
        "missions.title": "Core Responsibilities & Enterprise Missions",
        "missions.intro": "My apprenticeship rapidly exposed me to the strict constraints of real-world production. This versatility required me to simultaneously develop extreme rigor in technical execution (fine-tuning network settings) and an advisory posture during direct interactions with client infrastructures.",
        "missions.network.title": "Infrastructure Integration",
        "missions.network.desc": "I participated in the deployment of complex network topologies, from the physical layer up to active switching. This includes rack patching, positioning IoT/surveillance endpoints (NVRs), and logically securing their integration into the client's existing corporate network.",
        "missions.network.list1": "IP architecture topology planning, subnetting, and integrating edge IoT/camera endpoints.",
        "missions.network.list2": "Rack labeling, clean patching, and L2/L3 switch configuration (dedicated VLAN assignment and PoE budget management).",
        "missions.network.list3": "Provisioning encrypted gateways (VPN Servers) to guarantee secure, remote predictive maintenance.",
        "missions.network.list4": "On-site debugging (investigating broadcast storms, TDR testing on faulty copper links).",
        "missions.support.title": "IT Support & Continuous Delivery",
        "missions.support.desc": "Acting as a support technician for a highly heterogeneous fleet, I developed a structured diagnostic methodology (OSI model breakdown during network incidents). The constant goal: minimizing Mean Time To Recovery (MTTR) to ensure business continuity for end-users.",
        "missions.support.list1": "Active listening and remote diagnosis of complex hardware/software malfunctions using remote desktop tools.",
        "missions.support.list2": "Scheduled or emergency ('break-fix') on-site interventions involving component replacement (HDDs, RAM, NICs).",
        "missions.support.list3": "Systematic documentation of operations through meticulous intervention reports to ensure traceability.",
        "missions.support.list4": "Continuous knowledge transfer: expedited training for end-clients on operating their new supervision systems.",
        // PROJECT
        "project.title": "Capstone Academic Project — Hyperconverged Cluster (Proxmox & Ceph)",
        "project.intro": "To push my skills in distributed systems architecture, I conceptually designed and built a highly available (HA), fault-tolerant virtualization infrastructure from scratch. The matrix architecture required federating three bare-metal servers so that a hypervisor crash would never interrupt the hosted services (live-migrating VMs).",
        "project.badge": "Architecture & Clustering",
        "project.step1.title": "Network Isolation & OS Layer",
        "project.step1.desc": "Deployed the Debian-based Proxmox VE hypervisor across three distinct nodes. Enforced strict host-level firewalling and segmented traffic by creating bridge interfaces, ensuring that VM application traffic never congests the dedicated storage backplane.",
        "project.step2.title": "Federation and Quorum (Corosync)",
        "project.step2.desc": "Aggregated isolated nodes into a single clustered entity. Fine-tuned the Corosync multicast communication ring, which is vital for servers to instantly exchange health status (heartbeats) and prevent critical 'split-brain' scenarios.",
        "project.step3.title": "Distributed Object Storage (Ceph SDS)",
        "project.step3.desc": "Eliminated the Single Point of Failure (SPOF) inherent in traditional NAS/SAN setups by deploying the Ceph file system across all local disk arrays in the cluster. Synchronous block replication allows the cluster to physically survive the total hardware loss of a server without data corruption.",
        "project.step4.title": "Resilience & Chaos Testing",
        "project.step4.desc": "Simulated catastrophic failures (abruptly cutting power to a server) to verify that virtual machines automatically failed over to surviving nodes (HA mechanisms).",
        "project.result.label": "Final Assessment:",
        "project.result.text": "Successfully achieved a stable, fully redundant infrastructure. Gathered invaluable insights into the mechanics of distributed storage and disaster recovery orchestration during node outages.",
        // ACTIVITES - GENERAL
        "projects.title": "Projects",
        "projects.search_placeholder": "Search a project (e.g. MediaWiki, GLPI, Plex, Pi-hole)...",
        "projects.filter_all": "All",
        "projects.filter_network": "Network Infrastructure",
        "projects.filter_security": "Cybersecurity",
        "projects.filter_system": "Systems Administration",
        "projects.filter_web": "Web & Dev",
        "projects.intro": "This section aggregates a representative panel of my work. You will find both structural projects carried out during my academic training or corporate work-study, and personal 'labs' built autonomously to push my understanding of new technologies—particularly within the open-source ecosystem.",
        "projects.school_title": "📘 Academic Training Projects",
        "projects.pro_title": "💼 Professional Enterprise Deployments",
        "projects.personal_title": "🛠️ Personal Labs & Initiatives",
        "projects.goal_label": "Project Objective:",
        "projects.env_label": "Technical Environment:",
        "projects.material_label": "Hardware Resources:",
        "projects.result_label": "Final Outcome:",
        "projects.content_label": "Deliverable Details:",
        "projects.skills_label": "Key Skills Mobilized:",
        "skill.windows": "Windows Server Admin",
        "skill.linux": "GNU/Linux Admin",
        "skill.network": "Network Engineering",
        "skill.security": "Cybersecurity",
        "skill.helpdesk": "IT Support & Asset Mgmt",
        "skill.docker": "Containerization (Docker)",
        "skill.db": "Database Management",
        "skill.web": "Web Stack & Deployment",
        "skill.doc": "Technical Documentation",
        "skill.hardware": "Hardware Maintenance",
        "skill.ad": "Active Directory (AD DS)",
        "skill.m365": "Microsoft 365 Admin",
        "skill.scripting": "Automation / Scripting",
        "skill.vpn": "Remote Access & VPN",
        "skill.dns": "DNS Architecture",
        "projects.btn_detail": "Read the Full Case Study →",
        "projects.btn_pdf": "📄 Associated Documentation (PDF)",
        // ACTIVITES - CARDS
        "projects.mediawiki.title": "MediaWiki Deployment under Windows",
        "projects.mediawiki.goal": "Deploy a sustainable, scalable, and collaborative knowledge base to centralize technical expertise, standardize intervention procedures, and significantly reduce document search time for the IT team.",
        "projects.mediawiki.list1": "Preparation of the host server and deployment of the WAMP stack (XAMPP).",
        "projects.mediawiki.list2": "Secure creation of the <code>mediawiki</code> database via phpMyAdmin (user and privilege management).",
        "projects.mediawiki.list3": "Strict deployment of MediaWiki binaries into the <code>C:\\xampp\\htdocs\\mediawiki</code> directory.",
        "projects.mediawiki.list4": "Instance initialization via the web-based setup wizard and integration of the 'VisualEditor' extension for easier contributions.",
        "projects.mediawiki.list5": "Structuring an automated backup policy (regular SQL dumps) and securing sensitive directories.",
        "projects.glpi.title": "IT Asset & Helpdesk Management via GLPI",
        "projects.glpi.goal": "Implement a full ITSM solution (GLPI) to build an exhaustive inventory of all hardware and software computing assets, while rationalizing user support through an ITIL-structured incident ticketing portal.",
        "projects.glpi.list1": "Installation of a complete Web environment (Apache 2.4 / PHP 8 / MariaDB) on Windows.",
        "projects.glpi.list2": "Deployment of the specific <code>glpi</code> database and performance tuning within <code>php.ini</code>.",
        "projects.glpi.list3": "Execution of the GLPI installation routine in a dedicated root folder (<code>htdocs/glpi</code>).",
        "projects.glpi.list4": "Organizational configuration of GLPI: creating business entities, technician groups, and strictly defining profiles and access rights.",
        "projects.glpi.list5": "Full automation of hardware mapping using the FusionInventory extension and deploying reporting agents on client endpoints.",
        "projects.plex.title": "Plex Media Server on NAS",
        "projects.plex.goal": "Build a highly available, centralized private media center capable of streaming large media files to any device type (PC, Smart TV, mobiles), eliminating the constraints of local storage and VOD subscriptions.",
        "projects.plex.list1": "Software infrastructure setup via Docker on a dedicated Synology NAS.",
        "projects.plex.list2": "Advanced persistent volume mapping to dissociate media files from temporary transcoding data.",
        "projects.plex.list3": "Structured organization of metadata (Movies, Series, Music) and automated scraping/syncing.",
        "projects.plex.list4": "Granular permission management and library sharing across varied user profiles.",
        "projects.plex.list5": "Performance optimization via hardware transcoding activation (reducing CPU load during remote streams).",
        "projects.plex.result": "A robust central media service capable of transcoding multiple 4K streams simultaneously without stuttering.",
        "projects.pihole.title": "Network-Wide DNS Blocker (Pi-hole)",
        "projects.pihole.goal": "Sanitize overall network traffic by proactively blocking advertising domains, data trackers, and known malicious domains at the DNS level, silently protecting all connected devices (Smartphones, PCs, IoT).",
        "projects.pihole.list1": "Preparation and hardening of a Raspberry Pi (headless OS install, SSH lockdown, critical updates).",
        "projects.pihole.list2": "Deployment of the Pi-hole service and primary configuration of upstream DNS resolution.",
        "projects.pihole.list3": "Modification of the DHCP gateway (Router/ISP Box) to force DNS traffic toward the Pi-hole's static IP.",
        "projects.pihole.list4": "Importing aggressive blocklists filtering telemetry, ads, and polymorphic malware.",
        "projects.pihole.list5": "Setting up a routine for consulting logs and the admin dashboard to analyze blocked queries.",
        "projects.pihole.list6": "Log export configuration, whitelist/blacklist backups, and further IP hardening on the Raspberry.",
        "projects.pihole.result": "A clean network environment: massive visual removal of ads and radical reduction of intrusive tracking pings.",
        "projects.vpn.title": "Secure Remote Access (WireGuard VPN)",
        "projects.vpn.goal": "Design an encrypted access tunnel allowing secure connections to the corporate (or home) local network from an untrusted perimeter (e.g., public Wi-Fi), providing the exact same working conditions and security as being on-site.",
        "projects.vpn.list1": "In-depth securing of a Raspberry Pi host: UFW firewall configuration and Fail2Ban installation to thwart SSH bruteforcing.",
        "projects.vpn.list2": "Installation and parameterization of the WireGuard protocol, renowned for its modern cryptography and lightweight overhead.",
        "projects.vpn.list3": "Generation of private/public cryptographic key pairs and profile editing for remote endpoints (Windows, macOS, Android/iOS clients).",
        "projects.vpn.list4": "NAT routing configuration (dedicated UDP port forwarding) on the edge router and ensuring reachability via Dynamic DNS (DDNS).",
        "projects.vpn.list5": "Meticulous editing of firewall filtering rules (iptables) to restrict client access to specific subnets only (micro-segmentation).",
        "projects.vpn.list6": "Validation of Handshake establishment from an external 4G network and drafting client onboarding procedures.",
        "projects.vpn.result": "An invisible, unshakeable network bridge offering high throughput due to the protocol's kernel-space efficiency.",
        "projects.restaurant.btn_site": "🌐 Visit Live Website",
        "projects.restaurant.title": "Showcase Website Development (Restaurant)",
        "projects.restaurant.goal": "Deliver a clean, high-performance, and immediately understandable web showcase for a catering professional. The goal was to ditch heavy site builders in favor of targeted code, guaranteeing a load time under 2 seconds and excellent local SEO indexing.",
        "projects.restaurant.content": "The site is built on four pillars (Impactful Home, Interactive Menu, Logistics Info, Modular Contact). The design was engineered to maximize conversion rates (direct phone calls, online reservations).",
        "projects.restaurant.list1": "Wireframing and UI mockups, followed by strict integration using HTML5, modular CSS3 (Variables, Grid), and asynchronous JavaScript.",
        "projects.restaurant.list2": "Implementation of 'Mobile-First' concepts: the site scales perfectly from small smartphone screens to ultrawide monitors.",
        "projects.restaurant.list3": "WebPerf optimizations: modern image formats (compressed WebP), resource minification, aggressive browser caching.",
        "projects.restaurant.list4": "Development of a dynamic contact form protected by client-side validation systems and social media anchoring.",
        "projects.newsletter.title": "Newsletter Engine Development",
        "projects.newsletter.goal": "Operating on a strict zero-dollar software budget, the directive was to provide a non-profit organization the ability to reliably broadcast to over 500 subscribers without landing in spam filters, while also supplying open-rate metrics.",
        "projects.newsletter.list1": "Architecture and deployment of a headless Node.js backend web service, paired with a lightweight database (SQLite) for profile persistence.",
        "projects.newsletter.list2": "Application coupling with the Brevo (Sendinblue) REST API, acting as a trusted SMTP relay to ensure extremely high deliverability.",
        "projects.newsletter.list3": "Engineering a secure administration interface allowing managers to import contacts seamlessly.",
        "projects.newsletter.list4": "Continuous integration/deployment of the app container on Render.com, monitored by automated Keep-Alive pinging via UptimeRobot.",
        "projects.newsletter.list5": "Drafting of complete operational documentation (deployment, end-to-end usage, data backups).",
        "projects.newsletter.result": "A fully functional, documented, ready-to-use marketing engine for the non-profit, at an ongoing cost of €0/month.",
        // PROFESSIONAL ACTIVITIES
        "projects.support_glpi.title": "Helpdesk Administration via GLPI",
        "projects.support_glpi.goal": "Deliver proactive User Support (Tier 1/2) and exhaustively track the lifecycle of hardware and software incidents through the company's internal GLPI ticketing platform.",
        "projects.support_glpi.list1": "Triage, remote diagnosis, and resolution of incident tickets (network outages, software lockups).",
        "projects.support_glpi.list2": "Maintenance of the CMDB (Configuration Management Database): asset inventory and hardware assignments.",
        "projects.support_glpi.list3": "On-site proximal interventions for physical endpoint deployment and network terminal patching.",
        "projects.support_glpi.list4": "Creation and continual updating of the internal knowledge base (workaround procedures, user FAQs).",
        "projects.support_glpi.result": "An improved First Contact Resolution (FCR) rate and perfect traceability of technical interventions for quality assurance tracking.",
        "projects.m365_ad.title": "On-Premises Managed Services & M365",
        "projects.m365_ad.goal": "Orchestrate the modern hybrid workspace by coupling a localized Active Directory architecture (On-Premise) with the Microsoft 365 Cloud ecosystem for centralized identity management and collaboration tools.",
        "projects.m365_ad.list1": "Promotion of a Windows Server into a Domain Controller (AD DS) configuring core services (DNS, DHCP).",
        "projects.m365_ad.list2": "Architecting the Active Directory Tree (OUs), managing security groups, and enforcing Group Policy Objects (GPOs) to harden endpoints.",
        "projects.m365_ad.list3": "Creation and assignment of Microsoft 365 user licenses (Exchange Online, SharePoint, Teams configurations).",
        "projects.m365_ad.list4": "Workstation setup and domain join",
        "projects.m365_ad.result": "fully operational environment for all employees.",
        "projects.omada.title": "Network Supervision via TP-Link Omada SDN",
        "projects.omada.goal": "Deploy and administer a Software-Defined Networking (SDN) centralized architecture to drive the entire switching and routing fleet from a single cloud-based software console.",
        "projects.omada.list1": "Deployment of the Omada hybrid controller for the adoption and automatic ingestion of new network hardware across client sites.",
        "projects.omada.list2": "Link Aggregation (LACP) and port-based VLAN configuration (802.1Q) to isolate VoIP, Data, and Video Surveillance streams.",
        "projects.omada.list3": "Multi-site orchestration of batch firmware updates during scheduled nocturnal maintenance windows.",
        "projects.omada.list4": "Definition of SNMP alert thresholds, log retention history management, and regular performance diagnostics.",
        "projects.omada.result": "Absolute network observability (real-time monitoring), enabling immediate proactivity in the event of an uplink drop or congestion.",
        // VEILLE
        "blog.title": "Technological Lab & Watch",
        "blog.intro": "The IT ecosystem is subject to rapid skill obsolescence. The only countermeasure is rigorous and continuous tech watching. To consolidate my understanding of the state-of-the-art (Cybersecurity, New Systems Architectures, Cloud Environments), I aggregate my daily feeds via the <strong>Feeeeed</strong> mobile app, cross-referencing them with my professional networks on <strong>LinkedIn</strong> and content creators on <strong>YouTube</strong>.",
        "blog.read_more": "Read original article →",
        "blog.read_analysis": "Browse my synthesis note →",
        "blog.rss_title": "📡 Live RSS Feed — Industry Pulse",
        "blog.analysis.title": "📝 Retrospectives & Synthesis Notes",
        "blog.analysis.intro": "Passive reading is insufficient. I adopt an active dissection approach by writing synthesis notes on the most disruptive publications that influence my vision of systems engineering.",
        "blog.analysis.badge": "📖 Synthesis Note",
        "blog.analysis.summary_label": "<strong>Publication Macro-synthesis:</strong>",
        "blog.analysis.my_analysis": "<strong>Technical Decryption & Impact:</strong>",
        "blog.analysis4.date": "📅 Oct 10, 2025",
        "blog.analysis4.title": "The Dawn of Offensive AI: Industrializing Phishing",
        "blog.analysis4.source": "Source: Zataz",
        "blog.analysis4.summary": "In October 2025, the first massive phishing campaigns generated by Artificial Intelligence were detected. These attack vectors, stripped of usual syntax errors and contextually relevant, demonstrated a 30% higher compromise rate during Red Team audits. The emergence of offensive LLM frameworks (e.g., 'FraudGPT') has drastically lowered the technological barrier to entry for malicious actors.",
        "blog.analysis4.analysis": "This democratization of offensive AI is a tipping point. As a future administrator, this compels me to reconsider user training (the weak link) and, above all, to build unbypassable technical controls. We can no longer expect the user to spot a perfect email. The trust architecture must rely on heavy predictive anti-spam filtering, mandatory Multi-Factor Authentication (MFA), and conditional access strategies based on device compliance (MDM/Intune) rather than solely on user identity.",
        "blog.analysis6.date": "📅 Sept 15, 2025",
        "blog.analysis6.title": "Late 2025: The Phased Extinction of the Traditional VPN?",
        "blog.analysis6.source": "Source: Le Monde Informatique",
        "blog.analysis6.summary": "VPN architecture over IPSec or SSL tunnels, granting very broad network access once the perimeter is breached, is showing its age against the lateral movements of ransomware. CIOs are initiating a massive migration towards ZTNA (Zero Trust Network Access) solutions, a model where the encrypted tunnel no longer connects to the network, but lands directly in the proxy of the specific application required, for each individual session. A philosophy originally pushed by Google's BeyondCorp model.",
        "blog.analysis6.analysis": "This is the paradigmatic article that forced me to look into Zero Trust architectures. I had long considered VPNs (OpenVPN, WireGuard) as the panacea of remote access. I realized the fallacy of this approach regarding the risk of a compromised machine connected to the corporate VPN. From now on, I apply this micro-targeting even in my personal lab environments (segmented reverse proxies coupled with Authelia authentication services) to avoid exposing a direct link to the hypervisor backend.",
        "blog.stack_title": "📚 My Source Repositories",
        "blog.cat_law": "Legal Framework & Compliance",
        "blog.cat_ia": "AI Deployment & Sovereignty",
        "blog.article1.date": "📅 Nov 15, 2024",
        "blog.article1.source": "Source: IT-Connect",
        "blog.article1.title": "Windows Server 2025: What's New for Admins",
        "blog.article1.desc": "Microsoft is preparing the succession with Windows Server 2025. Hardened Active Directory, Hotpatching, better NVMe performance... An overview of the features that will impact daily systems administration.",
        "blog.article2.date": "📅 Oct 02, 2024",
        "blog.article2.source": "Source: CNIL",
        "blog.article2.title": "GDPR: What is the Economic Yield After 6 Years?",
        "blog.article2.desc": "Is privacy compliance a hindrance or an asset for businesses? A look back at the CNIL's findings and the concrete impacts for CIOs.",
        "blog.article3.date": "📅 Sept 28, 2024",
        "blog.article3.source": "Source: ZDNet",
        "blog.article3.title": "Digital Sovereignty: The Open Source AI Challenge",
        "blog.article3.desc": "With Mistral AI and Hugging Face, France holds strong cards against American tech giants. Open Source AI is a major stake for European technological independence.",
        // FOOTER
        "footer.desc": "BTS SIO Student, SISR Specialization. Passionate about systems administration, cybersecurity, and network architectures.",
        "footer.rights": "© 2026 Brieuc Métairie – Portfolio",
        "404.title": "404",
        "404.msg": "Oops! The page you are looking for does not exist or has been moved.",
        "404.back": "Return to Home Page"
    }
};
